version: '3'
services:
  etcd0:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    networks:
      - dbs
    volumes:
      - etcd0:/etcd_data
    deploy:
      placement:
        constraints:
        - node.labels.type9 == etcd0
      replicas: 1
     

    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd0:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  etcd1:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    volumes:
      - etcd1:/etcd_data
    networks:
      - dbs
    deploy:
      placement:
        constraints:
        - node.labels.type9 == etcd1
      replicas: 1     
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd1:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  etcd2:
    image: quay.io/coreos/etcd
    ports:
      - 2379
    volumes:
      - etcd2:/etcd_data
    networks:
      - dbs
    deploy:
      placement:
        constraints:
        - node.labels.type9 == etcd2
      replicas: 1
      
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd2
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd2:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd2:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380

volumes:
  etcd0:
  etcd1:
  etcd2:

networks:
  dbs:
    external: true

